# Generated by Django 3.2.21 on 2023-10-07 03:07

from django.db import migrations, models
import django.db.models.deletion
import saleor.core.utils.json_serializer
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0082_user_last_confirm_email_request'),
        ('product', '0189_merge_20230929_0857'),
        ('attribute', '0036_assignedproductattributevalue_product_data_migration'),
        ('channel', '0016_auto_20230816_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_metadata', models.JSONField(blank=True, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('neural_representation', models.BinaryField(blank=True, null=True)),
                ('cluster', models.IntegerField(blank=True, null=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_color', to='attribute.attributevalue')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_color', to='product.product')),
            ],
            options={
                'unique_together': {('product', 'color')},
            },
        ),
        migrations.CreateModel(
            name='ProductPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_preference', to='account.user')),
            ],
        ),
        migrations.CreateModel(
            name='ProductScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_score', to='product.product')),
                ('product_preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_score', to='preference.productpreference')),
            ],
            options={
                'unique_together': {('product_preference', 'product')},
            },
        ),
        migrations.CreateModel(
            name='WishlistVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_variant', to='preference.productpreference')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_variant', to='product.productvariant')),
            ],
            options={
                'unique_together': {('product_preference', 'variant')},
            },
        ),
        migrations.CreateModel(
            name='ProductColorScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('product_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_color_score', to='preference.productcolor')),
                ('product_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_color_score', to='preference.productscore')),
            ],
            options={
                'unique_together': {('product_score', 'product_color')},
            },
        ),
        migrations.CreateModel(
            name='ProductColorChannelListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_color_listings', to='channel.channel')),
                ('product_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_listings', to='preference.productcolor')),
            ],
            options={
                'ordering': ('pk',),
                'unique_together': {('product_color', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='DislikedProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disliked_product_color', to='preference.productcolor')),
                ('product_preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disliked_product_color', to='preference.productpreference')),
            ],
            options={
                'unique_together': {('product_preference', 'product_color', 'created_at')},
            },
        ),
    ]
