# Generated by Django 3.2.21 on 2023-10-07 03:07

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import saleor.core.utils.json_serializer


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0082_user_last_confirm_email_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_metadata', models.JSONField(blank=True, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='accommodation-logos')),
                ('website_url', models.URLField(blank=True, null=True)),
                ('isActive', models.BooleanField(default=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.address')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='accommodation',
            index=django.contrib.postgres.indexes.GinIndex(fields=['private_metadata'], name='accommodation_p_meta_idx'),
        ),
        migrations.AddIndex(
            model_name='accommodation',
            index=django.contrib.postgres.indexes.GinIndex(fields=['metadata'], name='accommodation_meta_idx'),
        ),
    ]
