# Generated by Django 3.2.21 on 2023-10-07 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0033_warehouse_external_reference'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={},
        ),
        migrations.RemoveField(
            model_name='stock',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='quantity_allocated',
        ),
        migrations.CreateModel(
            name='StockWTimePeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability_start', models.DateTimeField()),
                ('availability_end', models.DateTimeField()),
                ('quantity', models.IntegerField(default=0)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_w_time_period', to='warehouse.stock')),
            ],
            options={
                'unique_together': {('stock', 'availability_start', 'availability_end')},
            },
        ),
    ]
