# Generated by Django 3.2.21 on 2023-12-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0060_auto_20231007_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='rental_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='rental_start',
            field=models.DateTimeField(),
        ),
    ]
