# Generated by Django 3.2.21 on 2023-10-07 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0174_order_idx_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rental_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='rental_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
