# Generated by Django 3.2.21 on 2023-12-27 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0175_auto_20231007_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='rental_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='rental_start',
            field=models.DateTimeField(),
        ),
    ]
